{{- $xmppServer := include "jitsi-meet.name-prosody" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-meet.name-jvb" . }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  serviceName: {{ include "jitsi-meet.name-jvb" . }}
  replicas: {{ .Values.jvb.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jitsi-meet.name-jvb" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jitsi-meet.name-jvb" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "jitsi-meet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.jvb.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "jitsi-meet.name-jvb" . }}
          image: "{{ .Values.jvb.image.repository }}:{{ .Values.jvb.image.tag }}"
          imagePullPolicy: {{ .Values.jvb.image.pullPolicy }}
          env:
            - name: XMPP_SERVER
              value: {{ include "jitsi-meet.name-prosody" . }}
            {{- if .Values.jicofo.userAuth.enabled }}
            - name: JICOFO_AUTH_USER
              value: {{ .Values.jicofo.userAuth.name }}
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "jitsi-meet.name-jicofo-config" . }}
                  key: JICOFO_AUTH_PASSWORD
            {{- end }}
            {{- if .Values.jvb.userAuth.enabled }}
            - name: JVB_AUTH_USER
              value: {{ .Values.jvb.userAuth.name }}
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "jitsi-meet.name-jvb-config" . }}
                  key: JVB_AUTH_PASSWORD
            {{- end }}
            {{ if .Values.jicofo.componentSecret }}
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "jitsi-meet.name-jicofo-config" . }}
                  key: JICOFO_COMPONENT_SECRET
            {{ end }}
            - name: JVB_PORT
              value: "30300"
            {{- with .Values.jvb.environment }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: video
              containerPort: 30300
              protocol: UDP
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
            - name: config
              mountPath: "/var/app"
          lifecycle:
            podStart:
              exec:
                - /bin/bash
                - -c
                - cp /var/app/sip-communicator.properties /config/sip-communicator.properties
          resources:
            {{- toYaml .Values.jvb.resources | nindent 12 }}
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: config
          configMap:
            name: {{ template "jitsi-meet.name-jvb-config" . }}-cm
      {{- with .Values.jvb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.jvb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.jvb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
