{{- if .Values.web.hpa.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "jitsi-meet.name-web" . }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name:  {{ include "jitsi-meet.name-web" . }}
  maxReplicas: {{ .Values.web.hpa.maxReplicas }}
  minReplicas: {{ .Values.web.hpa.minReplicas }}
  metrics:
{{- with .Values.web.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ . }}
{{- end }}
{{- with .Values.web.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ . }}
{{- end }}
{{- end }}