apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.name-jvb" . }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - port: 30300
    protocol: UDP
    targetPort: 30300
    nodePort: 30300
  selector:
    app.kubernetes.io/name: {{ include "jitsi-meet.name-jvb" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
