jicofo:
  userAuth:
    enabled: true
    name: "focus"
    secret: dG90bwo=
  componentSecret: dG90bwo=
  environment:
    - name: TZ
      value: Europe/Amsterdam
    - name: JVB_BREWERY_MUC
      value: jvbbrewery
    - name: XMPP_DOMAIN
      value: meet.jitsi
    - name: XMPP_AUTH_DOMAIN
      value: auth.meet.jitsi
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.meet.jitsi
jvb:
  userAuth:
    enabled: true
    name: "jvb"
    secret: dG90bwo=
  environment:
    - name: TZ
      value: Europe/Amsterdam
    - name: JVB_BREWERY_MUC
      value: jvbbrewery
    - name: XMPP_DOMAIN
      value: meet.jitsi
    - name: XMPP_AUTH_DOMAIN
      value: auth.meet.jitsi
    - name: XMPP_MUC_DOMAIN
      value: muc.meet.jitsi
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "true"

prosody:
  environment:
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "true"
    - name: TZ
      value: Europe/Amsterdam
    - name: JVB_BREWERY_MUC
      value: jvbbrewery
    - name: XMPP_DOMAIN
      value: meet.jitsi
    - name: XMPP_AUTH_DOMAIN
      value: auth.meet.jitsi
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.meet.jitsi
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "true"
    - name: XMPP_MUC_DOMAIN
      value: muc.meet.jitsi

web:
  environment:
    - name: XMPP_SERVER
      value: localhost
    - name: JICOFO_AUTH_USER
      value: focus
    - name: XMPP_DOMAIN
      value: meet.jitsi
    - name: XMPP_AUTH_DOMAIN
      value: auth.meet.jitsi
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.meet.jitsi
    - name: XMPP_MUC_DOMAIN
      value: muc.meet.jitsi
    - name: TZ
      value: America/Los_Angeles
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "true"